import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  topbarWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: 52,
    // height: 64,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cccccc',
    borderStyle: 'solid',
    paddingTop: 16,
    // paddingTop: 14,
    // paddingBottom: 14,
    paddingBottom: 12,
    paddingLeft: 12,
    paddingRight: 12,
    boxSizing: 'border-box',
  },
  topbarWrapperOpacity: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: 52,
    backgroundColor: 'rgba(51, 51, 51, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(51, 51, 51, 0.1)',
    borderStyle: 'solid',
    paddingTop: 16,
    paddingBottom: 12,
    paddingLeft: 12,
    paddingRight: 12,
    boxSizing: 'border-box',
    top: 0,
    left: 0,
    zIndex: 1000,
  },
  topbarTitle: {
    // fontSize: 20,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333333',
    margin: 0,
    padding: 0,
  },
  topbarIcons: {
    flexDirection: 'row',
    gap: 4,
    margin: 0,
    padding: 0,
  },
  topbarIcon: {
    width: 24,
    height: 24,
    opacity: 1,
  },
  topbarSubSearchWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: 64,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#cccccc',
    borderStyle: 'solid',
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 12,
    paddingRight: 12,
    boxSizing: 'border-box',
  },
  topbarSubDivSearchWraaper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    height: 40,
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 20,
    paddingRight: 20,
    marginLeft: 13,
    borderWidth: 1,
    borderColor: '#cccccc',
    borderRadius: 10,
    borderStyle: 'solid',
    boxSizing: 'border-box',
  },
  topbarSerachPlaceholder: {
    fontSize: 16,
    color: '#cccccc',
  },
});

export default styles;
